name: Idee / Wunsch
description: Vorschlag für eine neue Funktion
labels: [enhancement]
body:
  - type: textarea
    id: idee
    attributes:
      label: Was wünschst du dir?
      description: Beschreibe kurz den Anwendungsfall.
    validations:
      required: true
